---
apiVersion: "v1"
kind: "List"
items:  

  - apiVersion: v1
    kind: Service
    metadata:
      name: jenkins
      labels:
        name: jenkins
    spec:
      type: "NodePort"
      selector:
        name: "jenkins"
      ports:
        -
          name: "jenkins"
          port: 80
          targetPort: 8080
          protocol: "TCP"
        -
          name: "jenkins-50000"
          port: 50000
          protocol: "TCP"

  - apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: jenkins
      labels: 
        name: jenkins
    spec:
      replicas: 2
      selector: 
        matchLabels:
          name: jenkins
      template:
        metadata:
          labels:
            name: jenkins
        spec:
          containers:
          - name: jenkins
            image: "jenkins:latest"
            ports:
              - containerPort: 8080
              - containerPort: 50000

  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: "jenkins"
      labels:
        name: jenkins
    spec:
      storageClassName: jenkins-storage
      capacity:
        storage: 5Gi
      accessModes:
        - ReadWriteOnce
      gcePersistentDisk:
        pdName: jenkins
        fsType: ext4

  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      name: "jenkins"
      labels:
        name: jenkins
    spec:
      storageClassName: jenkins-storage
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
